### ISSUE TITLE
IO does not work in threads other than 0

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/io#29]
IO does not work in any other thread than thread 0. To see this, type

```
!shell
IO_FindExecutable( "bash" );
```

**Comment by ssiccha** [comment]
Probably a bit late, but you can fix it by calling `MakeImmutable( IO );` from the main thread.

Apparently the `IO_*` functions try to access constants(?) defined in the record IO, which is owned by thread 0.

**Comment by markuspf** [comment]
IO has other problems with HPC-GAP in that it uses(ed?) global variables in the C code and leaks(ed?) even file descriptors.

Should be fixed really.

**Comment by ssiccha** [comment]
Ooh, that sounds unpleasant.

I'm trying to use it in an extra thread (i.e. not thread 0) to communicate with another non-GAP process. The first, very simple tests are running fine atm.

**Comment by markuspf** [comment]
What is that other non-gap process?

**Comment by ssiccha** [comment]
Basically a compiler I'd say. It's simulating things and we're just planning to send small messages from the compiler to GAP and vice versa.

**Comment by markuspf** [comment]
You could use ZeroMQ for that which is thread safe and everything.

**Comment by ssiccha** [comment]
Ah cool, thx for the hint. I'll have a look into the HPCGAP doc. (I've looked into IO since I wanted to get named pipes to work under GAP)

**Comment by fingolfin** [comment]
Resolved by PR #65 resp. 2511739678a81762bab7abfe214ca8fd7a50c5a1
