### ISSUE TITLE
Please update data at gap-system.org

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/io#39]
Hello:
Can you please update the data on the following webpage ?
http://www.gap-system.org/Packages/io.html

**Comment by fingolfin** [comment]
That page is not under my control; it gets update automatically whenever there is a GAP release, and it always refers to the latest version of the package that actually shipped with GAP.

**Comment by alex-konovalov** [comment]
Thanks @jgmbenoit for reporting this - this page is autogenerated from the metadata in the package's PackageInfo.g file after each release, so it will be updated as soon as it will be out.
