### ISSUE TITLE
Supporting ~ in paths

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/io#44]
IO package does not support `~` in paths, for example:

```
gap> ChangeDirectoryCurrent("/");
true
gap> Exec("pwd");
/
gap> ChangeDirectoryCurrent("~");
Error, <expr> must be 'true' or 'false' (not a boolean) in
  if IO_chdir( path )  then
    GAPInfo.DirectoryCurrent := Directory( path );
    return true;
else
    return fail;
fi; at /Users/alexk/gap4r8p3/pkg/io-4.4.6/gap/io.gi:1710 called from 
<function "ChangeDirectoryCurrent">( <arguments> )
 called from read-eval loop at line 3 of *stdin*
you can replace <expr> via 'return <expr>;'
brk> 
```

I have heard this from @james-d-mitchell who may have another example.

**Comment by fingolfin** [comment]
Of course it doesn't "support this". It's a low-level wrapper around POSIX APIs, while "~" is a high level feature of the shell. It also doesn't support "expansion of envariant variables, as in `cd $HOME`.

One could add support for this in the high level code, of course, such as `ChangeDirectoryCurrent`, but I am not convinced this is a good idea...

**Comment by fingolfin** [comment]
Closing as out of scope.

**Comment by alex-konovalov** [comment]
OK (maybe document this in the manual entry for `ChangeDirectoryCurrent`?).
