### ISSUE TITLE
Making documentation on system with case sensitive filesystem fails

### ISSUE THREAD

**Issue by markuspf** [gap-packages/io#53]
If I try making the docs for this package on linux the following happens:

 ```
➤ gmake doc
(echo 'Read("makedoc.g");' | /home/makx/dev/gap/bin/gap.sh -A -q)
Generating documentation in Directory("./doc/")
#I Composing XML document . . .
Error, Cannot include file ./doc/IO.xml.
```
This clearly is because the file is called `io.xml`, not `IO.xml`. I assume `AutoDoc` uses the package name as filename, so this comes down to the question: Is the official name of the package `io` or `IO`.

One fix is to rename `io.xml` to `IO.xml`, another is to rename the package in `PackageInfo.g`, yet another would be for @gap-packages/autodoc to lowercase package names for purposes of making a "canonical name".

**Comment by markuspf** [comment]
Maybe @sebasguts has an opinion on this, too?

**Comment by sebasguts** [comment]
I think introducing the standard to AutoDoc to only create lowercase filenames is sensitive.

However, one would have to check how many packages use AutoDoc, and how many manuals would have to be changed for this. I will still implement this patch now, just to see if there are any immediate problems from this.
@fingolfin What do you think about only lowercase filenames?
