### ISSUE TITLE
HTTP: please honour http proxy

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/io#78]
As Debian maintainer of the gap-io Debian package, I got a [bugreport](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920620l) that claims that the system's http proxy config is not respected by the current implementation.

**Comment by ChrisJefferson** [comment]
So, this is unlikely to happen as the IO package's implementation of http is a raw socket implementation, and adding support for proxys would be a huge amount of work. 

Longer term, we plan on adding an optional curlInterface package, and suggest people move to that package. That package (I hope, never checked) will use the system proxy by default, and also support https (which is, for us, a more immediate requirement)

**Comment by jgmbenoit** [comment]
quid  sftp or scp support ?

**Comment by fingolfin** [comment]
> quid sftp or scp support ?

Is that "quid" as in "money, pound", or "a portion of sth, mostly chewing tobacco", or "I want to show off my latin"? :-)

Seriously though: There is no, never was, never will be, support for any kind of encrypted communication in the io package, that includes https, sftp, scp, ftps, or whatever. It's simply out of scope.

As to HTTP: There only is a very limited HTTP/1.1 implementation in the io package, mostly added . It will never support HTTP/2.0 (see re: encryption, and not that HTTP/2.0 mandates TLS). Also, no advanced features: e.g. no proxy support, nor handling of redirects, no compression support, etc. For this reason, in a future version of the IO package, the HTTP support will be marked as deprecated.

If you have questions about [curlInterface](https://gap-packages.github.io/curlInterface/), I suggest to use [their issue tracker](https://github.com/gap-packages/curlInterface/issues), or email the package authors.

**Comment by jgmbenoit** [comment]
quid as "I am to lzy to type"
Whatever, I am on my way to close the debian bug.

**Comment by alex-konovalov** [comment]
BTW, the curInterface package is already included in the GAP distribution: https://www.gap-system.org/Packages/curlinterface.html

**Comment by jgmbenoit** [comment]
I have noticed. But, unfortunately, Debian is freezing so it is not reasonable to Debian-package it right know. I might consider it after the freeze.
