### ISSUE TITLE
Add Windows tests to CI setup

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/io#84]

**Comment by fingolfin** [comment]
I tried to do it using Travis in PR #83, but can't quite figure out how to install resp. use cygwin packages there (so I think I managed to install cygwin, but I don't know how to proceed from there). But if anybody wants to pick up those pieces and continue from there, be my guest, I won't work on this for now.

Of course it's also perfectly fine to use AppVeyor for this instead.

**Comment by wilfwilson** [comment]
This _might_ be easier now, given the https://github.com/gap-actions/setup-cygwin-for-gap action; GAP itself now uses this to test on Windows in GitHub Actions.
